on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 5 8 *'
    - cron: '0 22 12 8 *'
    - cron: '0 22 19 8 *'
    - cron: '0 22 26 8 *'
    - cron: '0 5 30 8 *'
    - cron: '0 22 2 9 *'
    - cron: '0 22 9 9 *'
    - cron: '30 5 16 9 *'
    - cron: '0 22 30 9 *'
    - cron: '30 0 8 10 *'
    - cron: '30 5 14 10 *'
    - cron: '0 5 18 10 *'
    - cron: '0 22 21 10 *'
    - cron: '0 22 28 10 *'
    - cron: '30 1 5 11 *'
    - cron: '30 1 12 11 *'
    - cron: '30 1 26 12 *'
    - cron: '30 1 31 12 *'
    - cron: '30 1 2 1 *'
    - cron: '30 1 14 1 *'
    - cron: '30 1 21 1 *'
    - cron: '30 1 4 2 *'
    - cron: '30 1 11 2 *'
    - cron: '30 1 18 2 *'
    - cron: '30 1 25 2 *'
    - cron: '30 1 4 3 *'
    - cron: '30 1 11 3 *'
    - cron: '30 1 18 3 *'
    - cron: '30 0 1 4 *'
    - cron: '30 0 8 4 *'
    - cron: '30 0 15 4 *'
    - cron: '30 0 22 4 *'
    - cron: '15 5 25 4 *'
    - cron: '30 0 29 4 *'
    - cron: '30 0 6 5 *'
    - cron: '30 0 13 5 *'
    - cron: '30 0 20 5 *'
    - cron: '30 1 28 5 *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          BOT_GITHUB_ACCESS_TOKEN: ${ secrets.BOT_GITHUB_ACCESS_TOKEN }
        run: python scraping/fivethirtyeight.py foo bar