on:
  workflow_dispatch:
  schedule:
    - cron: '30 11 13 8 *'
    - cron: '0 4 21 8 *'
    - cron: '0 4 28 8 *'
    - cron: '0 4 11 9 *'
    - cron: '30 11 17 9 *'
    - cron: '0 4 25 9 *'
    - cron: '0 4 2 10 *'
    - cron: '0 4 16 10 *'
    - cron: '30 11 22 10 *'
    - cron: '0 4 30 10 *'
    - cron: '30 7 6 11 *'
    - cron: '30 7 20 11 *'
    - cron: '30 7 27 11 *'
    - cron: '15 12 30 11 *'
    - cron: '30 7 4 12 *'
    - cron: '30 7 11 12 *'
    - cron: '15 12 14 12 *'
    - cron: '30 7 18 12 *'
    - cron: '30 7 26 12 *'
    - cron: '30 7 28 12 *'
    - cron: '30 7 1 1 *'
    - cron: '30 7 15 1 *'
    - cron: '30 7 22 1 *'
    - cron: '15 12 8 2 *'
    - cron: '30 7 12 2 *'
    - cron: '30 7 19 2 *'
    - cron: '30 7 26 2 *'
    - cron: '30 7 5 3 *'
    - cron: '30 7 12 3 *'
    - cron: '30 7 19 3 *'
    - cron: '30 6 2 4 *'
    - cron: '30 6 9 4 *'
    - cron: '30 6 16 4 *'
    - cron: '30 6 23 4 *'
    - cron: '30 6 30 4 *'
    - cron: '30 6 7 5 *'
    - cron: '30 6 15 5 *'
    - cron: '30 6 22 5 *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          BOT_GITHUB_ACCESS_TOKEN: ${ secrets.BOT_GITHUB_ACCESS_TOKEN }
        run: python data/collection/fivethirtyeight.py 