on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 13 8 *'
    - cron: '0 22 20 8 *'
    - cron: '0 22 27 8 *'
    - cron: '0 22 10 9 *'
    - cron: '30 5 17 9 *'
    - cron: '0 22 24 9 *'
    - cron: '0 22 1 10 *'
    - cron: '0 22 15 10 *'
    - cron: '30 5 22 10 *'
    - cron: '0 22 29 10 *'
    - cron: '30 6 5 11 *'
    - cron: '0 23 19 11 *'
    - cron: '0 23 26 11 *'
    - cron: '0 6 30 11 *'
    - cron: '0 23 3 12 *'
    - cron: '30 6 10 12 *'
    - cron: '15 6 14 12 *'
    - cron: '0 4 18 12 *'
    - cron: '30 1 26 12 *'
    - cron: '30 1 28 12 *'
    - cron: '0 23 31 12 *'
    - cron: '30 6 14 1 *'
    - cron: '30 6 21 1 *'
    - cron: '15 6 8 2 *'
    - cron: '0 23 11 2 *'
    - cron: '30 1 19 2 *'
    - cron: '30 1 26 2 *'
    - cron: '30 1 5 3 *'
    - cron: '30 1 12 3 *'
    - cron: '30 1 19 3 *'
    - cron: '30 0 2 4 *'
    - cron: '30 0 9 4 *'
    - cron: '30 0 16 4 *'
    - cron: '30 0 23 4 *'
    - cron: '30 0 30 4 *'
    - cron: '30 0 7 5 *'
    - cron: '30 0 15 5 *'
    - cron: '30 0 22 5 *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          BOT_GITHUB_ACCESS_TOKEN: ${ secrets.BOT_GITHUB_ACCESS_TOKEN }
        run: python scraping/fivethirtyeight.py foo bar