on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 13 8 *'
    - cron: '0 2 21 8 *'
    - cron: '0 2 28 8 *'
    - cron: '0 2 11 9 *'
    - cron: '30 9 17 9 *'
    - cron: '0 2 25 9 *'
    - cron: '0 2 2 10 *'
    - cron: '0 2 16 10 *'
    - cron: '30 9 22 10 *'
    - cron: '0 2 30 10 *'
    - cron: '30 10 5 11 *'
    - cron: '0 3 20 11 *'
    - cron: '0 3 27 11 *'
    - cron: '0 10 30 11 *'
    - cron: '0 3 4 12 *'
    - cron: '30 10 10 12 *'
    - cron: '0 10 14 12 *'
    - cron: '0 3 18 12 *'
    - cron: '0 3 26 12 *'
    - cron: '0 3 28 12 *'
    - cron: '0 3 1 1 *'
    - cron: '30 5 15 1 *'
    - cron: '30 5 22 1 *'
    - cron: '15 10 8 2 *'
    - cron: '30 5 12 2 *'
    - cron: '30 5 19 2 *'
    - cron: '30 5 26 2 *'
    - cron: '30 5 5 3 *'
    - cron: '30 5 12 3 *'
    - cron: '30 5 19 3 *'
    - cron: '30 4 2 4 *'
    - cron: '30 4 9 4 *'
    - cron: '30 4 16 4 *'
    - cron: '30 4 23 4 *'
    - cron: '30 4 30 4 *'
    - cron: '30 4 7 5 *'
    - cron: '30 4 15 5 *'
    - cron: '30 4 22 5 *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          BOT_GITHUB_ACCESS_TOKEN: ${ secrets.BOT_GITHUB_ACCESS_TOKEN }
        run: python scraping/fpl_review.py foo bar