on:
  workflow_dispatch:
  schedule:
    - cron: '30 20 5 8 *'
    - cron: '0 13 13 8 *'
    - cron: '0 13 20 8 *'
    - cron: '0 13 27 8 *'
    - cron: '0 20 30 8 *'
    - cron: '0 13 3 9 *'
    - cron: '0 13 10 9 *'
    - cron: '30 20 16 9 *'
    - cron: '0 13 1 10 *'
    - cron: '30 15 8 10 *'
    - cron: '30 20 14 10 *'
    - cron: '0 20 18 10 *'
    - cron: '0 13 22 10 *'
    - cron: '0 13 29 10 *'
    - cron: '30 16 5 11 *'
    - cron: '30 16 12 11 *'
    - cron: '30 16 26 12 *'
    - cron: '30 16 31 12 *'
    - cron: '30 16 2 1 *'
    - cron: '30 16 14 1 *'
    - cron: '30 16 21 1 *'
    - cron: '30 16 4 2 *'
    - cron: '30 16 11 2 *'
    - cron: '30 16 18 2 *'
    - cron: '30 16 25 2 *'
    - cron: '30 16 4 3 *'
    - cron: '30 16 11 3 *'
    - cron: '30 16 18 3 *'
    - cron: '30 15 1 4 *'
    - cron: '30 15 8 4 *'
    - cron: '30 15 15 4 *'
    - cron: '30 15 22 4 *'
    - cron: '15 20 25 4 *'
    - cron: '30 15 29 4 *'
    - cron: '30 15 6 5 *'
    - cron: '30 15 13 5 *'
    - cron: '30 15 20 5 *'
    - cron: '30 16 28 5 *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          BOT_GITHUB_ACCESS_TOKEN: ${ secrets.BOT_GITHUB_ACCESS_TOKEN }
        run: python scraping/fpl_gameweek.py foo bar