on:
  workflow_dispatch:
  schedule:
    - cron: '30 20 13 8 *'
    - cron: '0 13 21 8 *'
    - cron: '0 13 28 8 *'
    - cron: '0 13 11 9 *'
    - cron: '30 20 17 9 *'
    - cron: '0 13 25 9 *'
    - cron: '0 13 2 10 *'
    - cron: '0 13 16 10 *'
    - cron: '30 20 22 10 *'
    - cron: '0 13 30 10 *'
    - cron: '30 16 6 11 *'
    - cron: '30 16 20 11 *'
    - cron: '30 16 27 11 *'
    - cron: '15 21 30 11 *'
    - cron: '30 16 4 12 *'
    - cron: '30 16 11 12 *'
    - cron: '15 21 14 12 *'
    - cron: '30 16 18 12 *'
    - cron: '30 16 26 12 *'
    - cron: '30 16 28 12 *'
    - cron: '30 16 1 1 *'
    - cron: '30 16 15 1 *'
    - cron: '30 16 22 1 *'
    - cron: '15 21 8 2 *'
    - cron: '30 16 12 2 *'
    - cron: '30 16 19 2 *'
    - cron: '30 16 26 2 *'
    - cron: '30 16 5 3 *'
    - cron: '30 16 12 3 *'
    - cron: '30 16 19 3 *'
    - cron: '30 15 2 4 *'
    - cron: '30 15 9 4 *'
    - cron: '30 15 16 4 *'
    - cron: '30 15 23 4 *'
    - cron: '30 15 30 4 *'
    - cron: '30 15 7 5 *'
    - cron: '30 15 15 5 *'
    - cron: '30 15 22 5 *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          BOT_GITHUB_ACCESS_TOKEN: ${ secrets.BOT_GITHUB_ACCESS_TOKEN }
        run: python scraping/fpl_gameweek.py 